version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: airflow-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
    command: >
      bash -c "
        airflow db upgrade;
        airflow users create --username ${AIRFLOW_USER_NAME} --firstname admin --lastname admin --role Admin --email ${AIRFLOW_USER_EMAIL} --password ${AIRFLOW_USER_PASSWORD};
      "

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    ports:
      - "${AIRFLOW_UI_PORT}:8080"
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
    volumes:
      - ./dags:/opt/airflow/dags
    command: airflow scheduler

  nifi:
    image: apache/nifi:1.25.0
    container_name: nifi-server
    restart: unless-stopped
    ports:
      - "${NIFI_UI_PORT}:${NIFI_WEB_HTTP_PORT}"
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_WEB_HTTP_PORT}
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-data:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    restart: unless-stopped
    environment:
      - SPARK_MODE=${SPARK_MODE}
      - SPARK_RPC_AUTHENTICATION_ENABLED=${SPARK_RPC_AUTHENTICATION_ENABLED}
      - SPARK_RPC_ENCRYPTION_ENABLED=${SPARK_RPC_ENCRYPTION_ENABLED}
    ports:
      - "${SPARK_MASTER_UI_PORT}:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./apps:/opt/bitnami/spark/apps
      - ./data:/opt/bitnami/spark/data

volumes:
  postgres-data:
  nifi-conf:
  nifi-data:
  nifi-flowfile:
  nifi-content:
  nifi-provenance: